### ISSUE TITLE
com.github.tsingjyujing.geo.util.FileIO 没有找到

### ISSUE THREAD

**Issue by dzzxjl** [TsingJyujing/GeoScala#1]
请问这个功能是在版本更新中暂时去掉了吗？

**Comment by TsingJyujing** [comment]
应该是移到了测试类里面，你可以看看，我现在在外面，回去确认一下

**Comment by TsingJyujing** [comment]
已确认，在测试类中，这一部分功能不属于GeoScala的核心，仅仅是测试使用，如果你觉得好用，可以拷贝到自己的项目中去，或者使用hutool之类的第三方工具。
