### ISSUE TITLE
time: Double in TimeElement

### ISSUE THREAD

**Issue by dzzxjl** [TsingJyujing/GeoScala#2]
谢谢您的工作，请问我在处理轨迹序列数据时，time这个值是以怎样的形式来输入呢？谢谢

**Comment by TsingJyujing** [comment]
参考TimeElement类，以及GeoPointTimeSeries类

**Comment by TsingJyujing** [comment]
参考这个类：`com.github.tsingjyujing.geo.element.GeoPointTimeSeries`
点击[这里](https://github.com/TsingJyujing/GeoScala/blob/2b27e7bcbd9c47136816d35da1adb0e3fb6941cc/src/main/scala/com/github/tsingjyujing/geo/element/GeoPointTimeSeries.scala#L243)查看初始化方法。

Time一般是Double类型的，你可以尝试使用各种合适的时间，一般单位使用小时比较合适，这样计算出的速度就是常用的km/h。

我会尽快补全文档～
